---
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.41.1/vector-{{ vector_version }}.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
- name: Install vector package
  become: true
  ansible.builtin.yum:
    name:
      - vector-0.41.1-1.x86_64.rpm
- name: Config vector
  become: true
  ansible.builtin.template:
    src: "vector.yml"
    dest: "/etc/vector/vector.yml"
    mode: "0755"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  notify: Restart vector service
